name: Deploy Next.js to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Sesuaikan versi

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc  # Load PATH
            cd /var/www/fluenti
            git pull origin main
            export NVM_DIR=~/.nvm
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Jika pakai NVM
            node -v  # Debug
            npm -v   # Debug
            npm install
            npm run build
            pm2 restart fluenti
